on: [pull_request]
name: Testing
env:
  MODE: "dev"
jobs:
  debug:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Prepare
        run: ./docs/scripts/prepare-ci.sh
      - name: Install Drupal
        run: |
          systemctl enable mysql.service
          sleep 10
          systemctl enable apache2.service
          sleep 10
          vendor/bin/robo ci:install-drupal
      - name: Run Cypress tests
        run: vendor/bin/robo job:tests-cypress

#  code-standards:
#    runs-on: ubuntu-20.04
#    steps:
#      - uses: actions/checkout@v2
#      - name: Prepare
#        run: ./docs/scripts/prepare-ci.sh
#      - name: Check coding standards
#        run: vendor/bin/robo job:coding-standards
#
#  code-coverage:
#    runs-on: ubuntu-20.04
#    steps:
#      - uses: actions/checkout@v2
#      - name: Prepare
#        run: ./docs/scripts/prepare-ci.sh
#      - name: Install Drupal
#        run: |
#          sudo systemctl start mysql.service
#          sleep 10
#          sudo service apache2 start
#          sleep 10
#          vendor/bin/robo ci:install-drupal
#      - name: Assess code coverage
#        run: vendor/bin/robo job:coverage-report
#      - name: Create coverage folder
#        run: mkdir coverage
#      - name: Archive code coverage results
#        uses: actions/upload-artifact@v1
#        with:
#          name: coverage
#          path: coverage
#
#  phpunit-tests:
#    runs-on: ubuntu-20.04
#    steps:
#      - uses: actions/checkout@v2
#      - name: Prepare
#        run: ./docs/scripts/prepare-ci.sh
#      - name: Install Drupal
#        run: |
#          sudo systemctl start mysql.service
#          sleep 10
#          sudo service apache2 start
#          sleep 10
#          vendor/bin/robo ci:install-drupal
#      - name: Run PHPUnit tests
#        run: vendor/bin/robo job:tests-unit
#
#  cypress-tests:
#    runs-on: ubuntu-20.04
#    steps:
#      - uses: actions/checkout@v2
#      - name: Prepare
#        run: ./docs/scripts/prepare-ci.sh
#      - name: Install Drupal
#        run: |
#          sudo systemctl start mysql.service
#          sleep 10
#          sudo service apache2 start
#          sleep 10
#          vendor/bin/robo ci:install-drupal
#      - name: Run Cypress tests
#        run: vendor/bin/robo job:tests-cypress
